services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - RUST_LOG=info
    restart: unless-stopped